export interface DashboardComponent {
  id: string;
  type: string;
  displayName?: string;
  style?: string;
  text?: string;
  placeholder?: string;
  value?: string;
  options?: string[];
  newOption?: string[];
  headers?: string[];
  rows?: any[][];
  invert?: boolean;
  src?: string;
  alt?: string;
  href?: string;
  color?: string;
  fontSize?: string;
  fontWeight?: string;
  bgColor?: string;
  width?: string;
  height?: string;
  btnStyle?: string;
  iconClass?: string;
  controls?: boolean;
  autoplay?: boolean;
  items?: any[];
  active?: boolean;
  link?: string;
  icon?: string;
  label?: string;
  children?: DashboardComponent[];
  progress?: number;
  barColor?: string;
  alertType?: string;
  title?: string;
  content?: string;
  borderRadius?: string;
  objectFit?: 'fill' | 'contain' | 'cover' | 'none' | 'scale-down';
  class?: string;
  oddColumnColor?: string;
  evenColumnColor?: string;
  oddRowColor?: string;
  evenRowColor?: string;
  headerBgColor?: string;
  specificCellColor?: string;
  rowNumber?: number;
  colNumber?: number;
  highlightedRows?: { [rowIndex: number]: string };
  highlightedCols?: { [colIndex: number]: string };
  highlightedCells?: { [key: string]: string };
  headerColors?: string[];
  cellColors?: string[];
  checked?: boolean;
  radioStyle?: string;
  listType?: 'ordered' | 'unordered';
  action?: string;
  minWidth?: string;
  minHeight?: string;
  fontFamily?: string;
  fontStyle?: string;
  textDecoration?: string;
  textAlign?: string;
  textStyle?: 'p' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
  textTransform?: 'none' | 'uppercase' | 'lowercase' | 'capitalize' | 'sentence';
  flexDirection?: 'row' | 'column';
  justifyContent?: string;
  alignItems?: string;
  gap?: string;
  padding?: string;
  background?: string;
  shadow?: string;
  displayText?: string;
   properties?: any;
}